# Generated by Django 5.2.8 on 2025-11-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('authorId', models.CharField(max_length=64)),
                ('timestamp', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('attachment', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('projectId', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('isRead', models.BooleanField(default=False)),
                ('timestamp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ownerId', models.CharField(max_length=64)),
                ('startDate', models.CharField(max_length=30)),
                ('endDate', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('memberIds', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.CharField(max_length=64, unique=True)),
                ('messages', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('projectId', models.CharField(max_length=64)),
                ('startDate', models.CharField(max_length=30)),
                ('endDate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('shortDescription', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('acceptanceCriteria', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Draft', 'Draft'), ('Ready', 'Ready'), ('In Progress', 'In Progress'), ('Test', 'Test'), ('Done', 'Done'), ('Blocked', 'Blocked')], max_length=20)),
                ('priority', models.CharField(choices=[('1 - Critical', '1 - Critical'), ('2 - High', '2 - High'), ('3 - Moderate', '3 - Moderate'), ('4 - Low', '4 - Low')], max_length=20)),
                ('type', models.CharField(choices=[('Feature', 'Feature'), ('Defect', 'Defect'), ('Enhancement', 'Enhancement')], max_length=20)),
                ('storyPoints', models.IntegerField(blank=True, null=True)),
                ('assignedTeamId', models.CharField(blank=True, max_length=64, null=True)),
                ('assignedToId', models.CharField(blank=True, max_length=64, null=True)),
                ('businessOwnerId', models.CharField(blank=True, max_length=64, null=True)),
                ('testedById', models.CharField(blank=True, max_length=64, null=True)),
                ('projectId', models.CharField(max_length=64)),
                ('epicId', models.CharField(blank=True, max_length=64, null=True)),
                ('sprintId', models.CharField(blank=True, max_length=64, null=True)),
                ('release', models.CharField(blank=True, max_length=64, null=True)),
                ('plannedStartDate', models.CharField(blank=True, max_length=30, null=True)),
                ('plannedEndDate', models.CharField(blank=True, max_length=30, null=True)),
                ('actualStartDate', models.CharField(blank=True, max_length=30, null=True)),
                ('actualEndDate', models.CharField(blank=True, max_length=30, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('deadline', models.CharField(blank=True, max_length=30, null=True)),
                ('workNotes', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('relatedStoryIds', models.JSONField(blank=True, default=list, null=True)),
                ('createdById', models.CharField(max_length=64)),
                ('createdOn', models.CharField(max_length=30)),
                ('updatedById', models.CharField(max_length=64)),
                ('updatedOn', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StoryChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyId', models.CharField(max_length=64, unique=True)),
                ('messages', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('leadId', models.CharField(max_length=64)),
                ('memberIds', models.JSONField(default=list)),
                ('projectId', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
